### ISSUE TITLE
Currency Symbol?

### ISSUE THREAD

**Issue by mquinn123** [alcohol/iso4217#14]
It would be really great if a currency symbol was included in the currency array.

If you are interested in merging it in I will do the pull request.

Would this be acceptable:
        [
            'name' => 'Japanese Yen',
            'alpha3' => 'JPY',
            'numeric' => '392',
            'exp' => 0,
            'country' => 'JP',
            'symbol' => '¥'
        ],

**Comment by alcohol** [comment]
It is not that I am not interested, but it simply is not within the scope of ISO4217. This image aims to deliver just that, and nothing more.

**Comment by mquinn123** [comment]
Yeah I definitely see how its out of scope. I have been using intl to get currency symbols but its very dependent on the system install locales. Perhaps I will fork and add and extend the functionality. Thanks for all of your hard work for on this!
