### ISSUE TITLE
Which version doc iso 4217 used 2008 or 2015?

### ISSUE THREAD

**Issue by Sharabaddin** [alcohol/iso4217#8]
1.  Which version doc iso 4217 used 2008 or 2015?

2.  And whether it is possible to attach the version which was used or to lead the reference to the source. I think it will not be bad.

**Comment by alcohol** [comment]
The primary source of information (as mentioned in the README) was literally just https://en.wikipedia.org/wiki/ISO_4217. I merely try to reflect the current/latest information. There is no historic versioning or anything offered in this library. It also should be considered somewhat incomplete as I intentionally excluded some codes which do not really reflect actual currencies but rather trading units and such.

**Comment by Sharabaddin** [comment]
Tnx for answer. I want create program for arhive all currency all period))

**Comment by alcohol** [comment]
I am not sure I understand..? Sorry :-(
